# this template is taken from the site prototype based on Antora. It is replaced by AsciiBinder templates on the current version of the site.
site:
  title: Patriot Framework Documentation
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://patriot-framework.io/docs
  start_page: component-b::index.adoc
content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: master
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
